/*
 * Copyright 2008 University of California at Berkeley
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.rebioma.server.services;

import java.util.Date;

/**
 * OccurrenceUpdates generated by hbm2java
 */
public class OccurrenceUpdates implements java.io.Serializable {

  private Integer id;
  private Date lastupdate;

  public OccurrenceUpdates() {
  }

  public OccurrenceUpdates(Date lastupdate) {
    this.lastupdate = lastupdate;
  }

  public Integer getId() {
    return this.id;
  }

  public Date getLastupdate() {
    return this.lastupdate;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setLastupdate(Date lastupdate) {
    this.lastupdate = lastupdate;
  }

}
