package org.rebioma.server.services;

// Generated Mar 15, 2010 9:51:42 PM by Hibernate Tools 3.3.0.GA

/**
 * TaxonomicReviewer generated by hbm2java
 */
public class TaxonomicReviewer implements java.io.Serializable {

  private Integer id;
  private Integer userId;
  private String taxonomicField;
  private String taxonomicValue;
  private boolean isMarine;
  private boolean isTerrestrial;

  public TaxonomicReviewer() {
  }

  public TaxonomicReviewer(Integer userId, String taxonomicField,
      String taxonomicValue) {
    this.userId = userId;
    this.taxonomicField = taxonomicField;
    this.taxonomicValue = taxonomicValue;
  }

  public TaxonomicReviewer(Integer userId, String taxonomicField,
		String taxonomicValue, boolean isMarine, boolean isTerrestrial) {
	this.userId = userId;
	this.taxonomicField = taxonomicField;
	this.taxonomicValue = taxonomicValue;
	this.isMarine = isMarine;
	this.isTerrestrial = isTerrestrial;
}

public Integer getId() {
    return this.id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public Integer getUserId() {
    return this.userId;
  }

  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  public String getTaxonomicField() {
    return this.taxonomicField;
  }

  public void setTaxonomicField(String taxonomicField) {
    this.taxonomicField = taxonomicField;
  }

  public String getTaxonomicValue() {
    return this.taxonomicValue;
  }

  public void setTaxonomicValue(String taxonomicValue) {
    this.taxonomicValue = taxonomicValue;
  }

  public boolean getIsMarine() {
	  return isMarine;
  }
	
  public void setIsMarine(boolean isMarine) {
	  this.isMarine = isMarine;
  }
	
  public boolean getIsTerrestrial() {
	  return isTerrestrial;
  }
	
  public void setIsTerrestrial(boolean isTerrestrial) {
	  this.isTerrestrial = isTerrestrial;
  }

}
