package org.rebioma.server.services;

// Generated Feb 23, 2010 7:29:09 PM by Hibernate Tools 3.2.5.Beta

/**
 * Userroles generated by hbm2java
 */
public class UserRoles implements java.io.Serializable {

  private int id;
  private int userId;
  private int roleId;

  public UserRoles() {
  }

  public UserRoles(int userId, int roleId) {
    this.userId = userId;
    this.roleId = roleId;
  }

  public int getId() {
    return this.id;
  }

  public int getRoleId() {
    return this.roleId;
  }

  public int getUserId() {
    return this.userId;
  }

  public void setId(int id) {
    this.id = id;
  }

  public void setRoleId(int roleId) {
    this.roleId = roleId;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

}
