#!/bin/sh
APPDIR=`dirname $0`;
java -XstartOnFirstThread -Dgwt.args="-web -out www-test" -Xmx256M -cp "$APPDIR/src:$APPDIR/test:$APPDIR/bin:/Applications/eclipse-3.4/plugins/org.junit4_4.3.1/junit.jar:/Users/eighty/Java/google-web-toolkit-trunk-read-only/build/staging/gwt-mac-0.0.0/gwt-user.jar:/Users/eighty/Java/google-web-toolkit-trunk-read-only/build/staging/gwt-mac-0.0.0/gwt-dev-mac.jar" junit.textui.TestRunner org.rebioma.client.OccurrenceServiceTest "$@";
