/*
 * Copyright 2008 University of California at Berkeley
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 * 
 * http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.rebioma.client.bean;

/**
 * AscData generated by hbm2java
 */
public class AscData implements java.io.Serializable {

  private Integer id;
  private String dataType;
  private String fileName;
  private double southBoundary;
  private double westBoundary;
  private double northBoundary;
  private double eastBoundary;
  private String width;
  private String height;
  private double minValue;
  private double maxValue;
  private String description;
  private String units;
  private String variableType;
  private String year;
  private String envDataType;
  private String envDataSubtype;
  private String metadata;

  public AscData() {
  }

  public AscData(String fileName, double southBoundary, double westBoundary,
          double northBoundary, double eastBoundary, double minValue,
          double maxValue) {
    this.fileName = fileName;
    this.southBoundary = southBoundary;
    this.westBoundary = westBoundary;
    this.northBoundary = northBoundary;
    this.eastBoundary = eastBoundary;
    this.minValue = minValue;
    this.maxValue = maxValue;
  }

  public AscData(String dataType, String fileName, double southBoundary,
          double westBoundary, double northBoundary, double eastBoundary,
          String width, String height, double minValue, double maxValue,
          String description, String units, String variableType, String year,
          String envDataType, String envDataSubtype) {
    this.dataType = dataType;
    this.fileName = fileName;
    this.southBoundary = southBoundary;
    this.westBoundary = westBoundary;
    this.northBoundary = northBoundary;
    this.eastBoundary = eastBoundary;
    this.width = width;
    this.height = height;
    this.minValue = minValue;
    this.maxValue = maxValue;
    this.description = description;
    this.units = units;
    this.variableType = variableType;
    this.year = year;
    this.envDataType = envDataType;
    this.envDataSubtype = envDataSubtype;
  }

  public String getDataType() {
    return this.dataType;
  }

  public String getDescription() {
    return this.description;
  }

  public double getEastBoundary() {
    return this.eastBoundary;
  }

  public String getEnvDataSubtype() {
    return this.envDataSubtype;
  }

  public String getEnvDataType() {
    return this.envDataType;
  }

  public String getFileName() {
    return this.fileName;
  }

  public String getHeight() {
    return this.height;
  }

  public Integer getId() {
    return this.id;
  }

  public double getMaxValue() {
    return this.maxValue;
  }

  public String getMetadata() {
    return metadata;
  }

  public double getMinValue() {
    return this.minValue;
  }

  public double getNorthBoundary() {
    return this.northBoundary;
  }

  public double getSouthBoundary() {
    return this.southBoundary;
  }

  public String getUnits() {
    return this.units;
  }

  public String getVariableType() {
    return this.variableType;
  }

  public double getWestBoundary() {
    return this.westBoundary;
  }

  public String getWidth() {
    return this.width;
  }

  public String getYear() {
    return this.year;
  }

  public void setDataType(String dataType) {
    this.dataType = dataType;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public void setEastBoundary(double eastBoundary) {
    this.eastBoundary = eastBoundary;
  }

  public void setEnvDataSubtype(String envDataSubtype) {
    this.envDataSubtype = envDataSubtype;
  }

  public void setEnvDataType(String envDataType) {
    this.envDataType = envDataType;
  }

  public void setFileName(String fileName) {
    this.fileName = fileName;
  }

  public void setHeight(String height) {
    this.height = height;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setMaxValue(double maxValue) {
    this.maxValue = maxValue;
  }

  public void setMetadata(String metadata) {
    this.metadata = metadata;
  }

  public void setMinValue(double minValue) {
    this.minValue = minValue;
  }

  public void setNorthBoundary(double northBoundary) {
    this.northBoundary = northBoundary;
  }

  public void setSouthBoundary(double southBoundary) {
    this.southBoundary = southBoundary;
  }

  public void setUnits(String units) {
    this.units = units;
  }

  public void setVariableType(String variableType) {
    this.variableType = variableType;
  }

  public void setWestBoundary(double westBoundary) {
    this.westBoundary = westBoundary;
  }

  public void setWidth(String width) {
    this.width = width;
  }

  public void setYear(String year) {
    this.year = year;
  }

}
