package org.rebioma.client.bean;

import java.io.Serializable;
import java.util.Date;

// Generated May 25, 2010 8:09:07 PM by Hibernate Tools 3.3.0.GA

/**
 * AscModel generated by hbm2java
 */
public class AscModel implements Serializable {

  private Integer id;
  private String acceptedSpecies;
  private String modelLocation;
  private String indexFile;
  private Date date;
  
  public AscModel() {
  }

  public AscModel(String acceptedSpecies, String modelLocation, String indexFile) {
    this.acceptedSpecies = acceptedSpecies;
    this.modelLocation = modelLocation;
    this.indexFile = indexFile;
  }

  public String getAcceptedSpecies() {
    return this.acceptedSpecies;
  }

  public Integer getId() {
    return this.id;
  }

  public String getIndexFile() {
    return this.indexFile;
  }

  public String getModelLocation() {
    return this.modelLocation;
  }
  
  public Date getDate() {
	return date;
  }

  public void setAcceptedSpecies(String acceptedSpecies) {
    this.acceptedSpecies = acceptedSpecies;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public void setIndexFile(String indexFile) {
    this.indexFile = indexFile;
  }

  public void setModelLocation(String modelLocation) {
    this.modelLocation = modelLocation;
  }

  public void setDate(Date date) {
	this.date = date;
  }
  
}
