package org.rebioma.client.bean;

import java.io.Serializable;
import java.util.Date;

// Generated Nov 20, 2008 10:22:21 AM by Hibernate Tools 3.2.2.GA

/**
 * OccurrenceComments generated by hbm2java
 */
public class OccurrenceComments implements Serializable {

  private int id;
  private int occurrenceId;
  private int userId;
  private String userComment;
  private Date dateCommented;
  private String userEmail;

  public OccurrenceComments() {
  }

  public OccurrenceComments(int occurrenceId, int userId, String userComment) {
    this.occurrenceId = occurrenceId;
    this.userId = userId;
    this.userComment = userComment;
  }

  public Date getDateCommented() {
    return dateCommented;
  }

  public int getId() {
    return this.id;
  }

  public int getOccurrenceId() {
    return this.occurrenceId;
  }

  public String getUserComment() {
    return this.userComment;
  }

  public String getUserEmail() {
    return userEmail;
  }

  public int getUserId() {
    return this.userId;
  }

  public void setDateCommented(Date dateCommented) {
    this.dateCommented = dateCommented;
  }

  public void setId(int id) {
    this.id = id;
  }

  public void setOccurrenceId(int occurrenceId) {
    this.occurrenceId = occurrenceId;
  }

  public void setUserComment(String userComment) {
    this.userComment = userComment;
  }

  public void setUserEmail(String userEmail) {
    this.userEmail = userEmail;
  }

  public void setUserId(int userId) {
    this.userId = userId;
  }

}
